name: Portfolio CI/CD

# Trigger workflow on pushes to main
on:
  push:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Set up Docker buildx
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # 3️⃣ Run tests
      - name: Run tests
        run: |
          chmod +x tests/run-tests.sh
          ./tests/run-tests.sh

      # 4️⃣ Build Docker image
      - name: Build Docker image
        run: docker build -t portfolio:ci .

      # Optional: List Docker images to confirm build
      - name: List Docker images
        run: docker images

