name: Portfolio CI/CD

on:
  push:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Run tests
        run: |
          chmod +x tests/run-tests.sh
          ./tests/run-tests.sh

      - name: Build Docker image
        run: docker build -t portfolio:ci .

      # Skip actual docker-compose up, just build and test

